name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Comparador de Lista Web CI Pipeline"]
    types: [completed]
    branches: ["main", "master"]

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      # Baixa o artefato gerado no workflow de CI
      - name: Download Build Artifact from CI
        uses: dawidd6/action-download-artifact@d63b86af1b34672e53c440b1b83979861906bad7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: "Comparador de Lista Web CI Pipeline"
          run_id: ${{ github.event.workflow_run.id }}
          name: comparador-lista-web
          path: ./dist

      # Prepara o diretório para o GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346